from . import sale_order
from . import delivery_slot
from . import delivery_carrier
from . import stock_alert
from . import res_partner
from . import sale_order_line
from . import loyalty_program
from . import product_template
from . import customer_account
